springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging.level.com.smartjob.users: DEBUG
spring:
  application:
    name: "users"
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: always  # This enables data source initialization
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

jwt:
  issuer: www.smartjob.com
  secret: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 #hash sha256: test
  expired-time: 900000

validations:
  password:
    regex: ^(?=.*[a-zA-Z])(?=.*\d).{6,}$